# Generated by Django 5.1.1 on 2024-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_itementry_delete_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementry',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
