# Generated by Django 5.1.1 on 2024-09-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itementry_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itementry',
            old_name='name',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='itementry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itementry',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itementry',
            name='stock',
        ),
    ]
