# Generated by Django 5.1.1 on 2024-09-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_itementry_nama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itementry',
            old_name='nama',
            new_name='name',
        ),
        migrations.AddField(
            model_name='itementry',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='itementry',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itementry',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
