# Generated by Django 5.1.1 on 2024-09-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_nama_itementry_name_itementry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementry',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
