# Generated by Django 5.1.1 on 2024-09-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_itementry_rating_alter_itementry_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemEntry',
            new_name='Product',
        ),
    ]
