# Generated by Django 5.1.1 on 2024-10-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
